version: "20.10.8"
services:
  app:
    container_name: sdc-overview
    build: .
    ports:
      - '80:3001'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://andrewhang@password/overview
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andrewhang
      POSTGRES_PASSWORD: password
      POSTGRES_DB: overview



